project_id = "jiegopvbwpyfohhfvmwo"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
port = 54325

[auth]
port = 54326

[edge_runtime]
port = 54327

[realtime]
port = 54328

[functions.create-checkout]
verify_jwt = true
# Disabled for internal membership system

[functions.check-subscription]
verify_jwt = true
# Disabled for internal membership system  

[functions.customer-portal]
verify_jwt = true
# Disabled for internal membership system

[functions.send-confirmation-email]
verify_jwt = true

[functions.create-member]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.sync-image-to-local]
verify_jwt = true

[functions.create-test-accounts]
verify_jwt = true
# SECURITY: Requires admin authentication to prevent unauthorized account creation

[functions.admin-health-check]
verify_jwt = true
# SECURITY: Requires authentication to prevent information disclosure

[functions.admin-auth-validation]
verify_jwt = true
# SECURITY: Requires authentication for token validation

[functions.validate-file-upload]
verify_jwt = true
# SECURITY: Requires authentication to prevent storage abuse