-- Inserir as modelos existentes no banco de dados com UUIDs gerados automaticamente
INSERT INTO public.models (
  name, age, location, price, description, height, measurements, 
  hair, eyes, nationality, image, services, characteristics, availability, rating, reviews
) VALUES 
(
  'Sofia', 
  24, 
  'Mayfair', 
  '£500/hour',
  'Sofia is an elegant and sophisticated companion with a passion for fine dining and cultural events. She brings warmth and intelligence to every encounter.',
  '5''7"',
  '34-24-36',
  'Brunette',
  'Brown',
  'Brazilian',
  '/src/assets/model1.jpg',
  ARRAY['Dinner Companion', 'Event Escort', 'Private Meetings'],
  ARRAY['High Class', 'Bi Sexual', 'Open Minded', 'Young', 'Brunette', 'Slim'],
  'available',
  4.9,
  156
),
(
  'Isabella',
  26,
  'Kensington',
  '£600/hour',
  'Isabella is a charming and well-educated companion who excels in social situations. Her European elegance and wit make her the perfect choice for any occasion.',
  '5''6"',
  '36-25-37',
  'Blonde',
  'Blue',
  'French',
  '/src/assets/model2.jpg',
  ARRAY['Social Events', 'Business Dinners', 'Travel Companion'],
  ARRAY['High Class', 'Blonde', 'Slim', 'Natural'],
  'available',
  4.8,
  203
),
(
  'Victoria',
  23,
  'Chelsea',
  '£550/hour',
  'Victoria combines youthful energy with remarkable sophistication. Her background in dance and performance arts adds grace to her already captivating presence.',
  '5''8"',
  '32-23-35',
  'Auburn',
  'Green',
  'British',
  '/src/assets/model3.jpg',
  ARRAY['Cultural Events', 'Dance Performances', 'Art Exhibitions'],
  ARRAY['Young', 'Artistic', 'Graceful', 'Energetic'],
  'available',
  4.7,
  134
),
(
  'Anastasia',
  28,
  'Belgravia',
  '£700/hour',
  'Anastasia brings international flair with her Russian heritage and London sophistication. Her experience in luxury hospitality ensures every moment is perfectly curated.',
  '5''9"',
  '34-24-36',
  'Platinum Blonde',
  'Blue',
  'Russian',
  '/src/assets/model4.jpg',
  ARRAY['Luxury Events', 'International Travel', 'Corporate Functions'],
  ARRAY['International', 'Luxurious', 'Experienced', 'Sophisticated'],
  'available',
  4.9,
  178
),
(
  'Luisa',
  27,
  'Notting Hill',
  '£650/hour',
  'Luisa brings exotic allure with her Mediterranean heritage and sophisticated London upbringing. Her multilingual abilities make her fascinating company.',
  '5''7"',
  '34-25-35',
  'Black',
  'Dark Brown',
  'Italian-British',
  '/src/assets/luisa1.jpg',
  ARRAY['International Events', 'Wine Tastings', 'Cultural Tours'],
  ARRAY['Exotic', 'Worldly', 'Sophisticated', 'Multilingual'],
  'available',
  4.8,
  112
),
(
  'Kate',
  25,
  'Kensington',
  '£580/hour',
  'Kate embodies modern British elegance with her classic features and contemporary style. She excels in both corporate and creative environments.',
  '5''8"',
  '32-24-35',
  'Blonde',
  'Blue',
  'British',
  '/src/assets/kate1.jpg',
  ARRAY['Business Events', 'Fashion Week', 'Private Parties'],
  ARRAY['Professional', 'Elegant', 'Versatile', 'Modern'],
  'available',
  4.9,
  134
);