-- Inserir as modelos existentes no banco de dados com UUIDs válidos
INSERT INTO public.models (
  name, age, location, price, description, height, measurements, 
  hair, eyes, nationality, image, services, characteristics, availability, rating, reviews
) VALUES 
(
  'Isabella', 
  25, 
  'Mayfair, London', 
  'From £800/hour',
  'Isabella is the epitome of elegance and sophistication. With her classical beauty and refined demeanor, she brings a touch of aristocratic grace to every occasion. Her education in art history and fluency in multiple languages make her the perfect companion for cultural events, gallery openings, and intimate dinner parties.',
  '5''7"',
  '34C-24-35',
  'Brunette',
  'Hazel',
  'British',
  '/images/model1.jpg',
  ARRAY['Dinner Dates', 'Cultural Events', 'Travel Companion'],
  ARRAY['Elegant', 'Sophisticated', 'Cultured'],
  'Available',
  4.9,
  127
),
(
  'Sophie',
  24,
  'Knightsbridge, London',
  'From £900/hour',
  'Sophie captivates with her stunning blonde beauty and vivacious personality. A former model with an impeccable sense of style, she effortlessly commands attention at any social gathering. Her warmth and charm make her equally comfortable at high-profile events or intimate settings.',
  '5''9"',
  '32B-25-36',
  'Blonde',
  'Blue',
  'British',
  '/images/model2.jpg',
  ARRAY['Social Events', 'Fashion Shows', 'Business Functions'],
  ARRAY['Charming', 'Stylish', 'Confident'],
  'Available',
  4.8,
  98
),
(
  'Victoria',
  26,
  'Chelsea, London',
  'From £1000/hour',
  'Victoria embodies timeless beauty with her striking features and regal presence. With a background in classical music and dance, she brings artistic flair to every encounter. Her intelligence and poise make her the ideal companion for discerning gentlemen who appreciate refined company.',
  '5''8"',
  '34B-24-34',
  'Auburn',
  'Green',
  'British',
  '/images/model3.jpg',
  ARRAY['Theatre', 'Fine Dining', 'Private Events'],
  ARRAY['Artistic', 'Intelligent', 'Graceful'],
  'Available',
  4.9,
  156
),
(
  'Arabella',
  23,
  'Belgravia, London',
  'From £850/hour',
  'Arabella is a breath of fresh air with her youthful energy and natural beauty. Despite her young age, she possesses remarkable maturity and social grace. Her passion for literature and philosophy creates engaging conversations, while her spontaneous spirit brings excitement to any occasion.',
  '5''6"',
  '32C-23-34',
  'Dark Brown',
  'Brown',
  'British',
  '/images/model4.jpg',
  ARRAY['Literary Events', 'Weekend Getaways', 'Casual Dining'],
  ARRAY['Youthful', 'Engaging', 'Spirited'],
  'Available',
  4.7,
  89
),
(
  'Luisa',
  27,
  'Notting Hill, London',
  'From £950/hour',
  'Luisa brings exotic allure with her Mediterranean heritage and sophisticated London upbringing. Her multilingual abilities and international perspective make her fascinating company for worldly gentlemen. She excels in both intimate conversations and grand social occasions.',
  '5''7"',
  '34C-25-35',
  'Black',
  'Dark Brown',
  'Italian-British',
  '/images/luisa1.jpg',
  ARRAY['International Events', 'Wine Tastings', 'Cultural Tours'],
  ARRAY['Exotic', 'Worldly', 'Sophisticated'],
  'Available',
  4.8,
  112
),
(
  'Kate',
  25,
  'Kensington, London',
  'From £900/hour',
  'Kate embodies modern British elegance with her classic features and contemporary style. Her background in business and fashion gives her insight into both corporate and creative worlds. She is equally at home in boardrooms and ballrooms.',
  '5''8"',
  '32B-24-35',
  'Blonde',
  'Blue',
  'British',
  '/images/kate1.jpg',
  ARRAY['Business Events', 'Fashion Week', 'Private Parties'],
  ARRAY['Professional', 'Elegant', 'Versatile'],
  'Available',
  4.9,
  134
);